#--------------------------------------------------
# Project:
# Purpose:
#--------------------------------------------------

.PHONY: run test

## default target
run: 
	racket main.rkt

test:
	raco test main.rkt
