#--------------------------------------------------
# Project:
# Purpose:
#--------------------------------------------------

.PHONY: all test

all: main

main:
	racket nn.rkt

test:
	raco test main.rkt

